repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
      - id: linting
        name: "Linting"
        files: js
        language: system
        entry: /bin/sh -c "cd js && npm run lint:ci"
