version: '3.0'

services:
  server:
    build:
      context: js
    environment:
      - BACKEND_AUTH_TOKEN=change_me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/live"]
    ports:
      - 3000:3000

  client:
    build:
      context: js
    entrypoint: ["npm", "run", "client"]
    depends_on:
      - backend
    ports:
      - 57220:57220/udp
    environment:
      - SC_HOST=host.docker.internal
      - SC_PORT=${SC_PORT:-57120}
      - BACKEND_ADDRESS=http://server:3000
      - BACKEND_AUTH_TOKEN=change_me
