version: '3.0'

services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/root/remote_modular_frontend
  backend:
    build: .
    entrypoint: [ "node", "server.js" ]
    environment:
      - BACKEND_AUTH_TOKEN=change_me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/live"]
    ports:
      - 3000:3000
  client:
    build: .
    depends_on:
      - backend
    ports:
      - 57220:57220/udp
    environment:
      - SC_HOST=host.docker.internal
      - SC_PORT=57120
      - BACKEND_ADDRESS=http://backend:3000
      - BACKEND_AUTH_TOKEN=change_me
