version: '3.0'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.small
    ports:
      - 57220:57220/udp
    environment:
      - SC_HOST=host.docker.internal
      - SC_PORT=57120
      - BACKEND_ADDRESS
      - BACKEND_AUTH_TOKEN
