FROM node:14-alpine

# does not include a static build of the frontend

WORKDIR /root/web_rtc_gui

RUN apk add curl

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY server.js .

COPY client.js .

ENTRYPOINT [ "node", "client.js" ]
