version: '3.0'

services:
  backend:
    build:
      context: js
    entrypoint: [ "npm", "run", "server"]
    environment:
      - BACKEND_AUTH_TOKEN=${BACKEND_AUTH_TOKEN:-change_me}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/live"]
    ports:
      - 3000:3000
