version: '3.0'

services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/root/web_rtc_gui

  backend:
    build:
      context: .
      dockerfile: Dockerfile.small
    entrypoint: [ "npm", "run", "server" ]
    volumes:
      - ./server.ts:/root/web_rtc_gui/server.ts
      - ./communication.ts:/root/web_rtc_gui/communication.ts
    environment:
      - BACKEND_AUTH_TOKEN=change_me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/live"]
    ports:
      - 3000:3000

  client:
    build:
      context: .
      dockerfile: Dockerfile.small
    depends_on:
      - backend
    volumes:
      - ./client.ts:/root/web_rtc_gui/client.ts
      - ./communication.ts:/root/web_rtc_gui/communication.ts
    ports:
      - 57220:57220/udp
    environment:
      - SC_HOST=host.docker.internal
      - SC_PORT=57120
      - BACKEND_ADDRESS=http://backend:3000
      - BACKEND_AUTH_TOKEN=change_me
