version: '3.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.full
    entrypoint: [ "node", "server.js"]
    environment:
      - BACKEND_AUTH_TOKEN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/live"]
    ports:
      - 3000:3000
