FROM node:14-alpine

# does not include a static build of the frontend

WORKDIR /root/web_rtc_gui

RUN apk add curl

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY server.ts .

COPY client.ts .

COPY communication.ts .

ENTRYPOINT [ "npm", "run", "client" ]
