name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: "npm"
        cache-dependency-path: |
          js/package-lock.json
    - run: npm ci
      working-directory: js
    - uses: pre-commit/action@v2.0.3
